name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: VelocityDiscord
          path: ./target/velocity-discord-*.jar
